apiVersion: v1
kind: Service
metadata:
  name: {{ include "byoc.fullname" . }}
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    {{- include "byoc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "byoc.selectorLabels" . | nindent 4 }}
